const ADD_CRYPTO = 'ADD_CRYPTO';
const ADD_CRYPTO_FAILUR = 'ADD_CRYPTO_FAILUR';
const ADD_CRYPTO_SUCCESS = 'ADD_CRYPTO_SUCCESS';
const REMOVE_CRYPTO = 'REMOVE_CRYPTO';
const GET_CRYPTO = 'GET_CRYPTO';
const GET_CRYPTO_FAILUR = 'GET_CRYPTO_FAILUR';
const GET_CRYPTO_SUCCESS = 'GET_CRYPTO_SUCCESS';

export {
  ADD_CRYPTO,
  ADD_CRYPTO_FAILUR,
  ADD_CRYPTO_SUCCESS,
  REMOVE_CRYPTO,
  REMOVE_CRYPTO_FAILUR,
  REMOVE_CRYPTO_SUCCESS,
  GET_CRYPTO,
  GET_CRYPTO_FAILUR,
  GET_CRYPTO_SUCCESS,
};
